### ISSUE TITLE
bots shit

### ISSUE THREAD

**Issue by agashehaweyh** [Sciencentistguy/bonkbot#1]
bonk this
enemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middleenemy missing middle

**Comment by Sciencentistguy** [comment]
Alex please don't spam the issue tracker :expressionless:
